
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app/src/saas  # Set working directory correctly
    environment:
      - DEBUG=True
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
