name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up SSH Key
      shell: bash
      run: |
        echo "${{ secrets.EC2_KEY }}" > ~/Saas.pem
        chmod 400 ~/Saas.pem

    - name: Deploy Code
      shell: bash
      run: |
        # Copy all project files except .git to EC2
        rsync -avz --exclude='.git' --exclude='.github' -e "ssh -i ~/Saas.pem -o StrictHostKeyChecking=no" . ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/saas

    - name: Set Permissions
      shell: bash
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/Saas.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
        sudo chown -R ${{ secrets.EC2_USER }}:${{ secrets.EC2_USER }} /home/${{ secrets.EC2_USER }}/saas &&
        sudo chmod -R 775 /home/${{ secrets.EC2_USER }}/saas
        "


    - name: Start Docker Containers
      shell: bash
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/Saas.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
          cd /home/${{ secrets.EC2_USER }}/saas &&
          sudo docker-compose up --build -d
        "
